[project]
authors = ["Rohit Goswami <rog32 [at] hi.is>"]
channels = ["conda-forge"]
description = "Pybind11 meson-python pytest demo"
name = "pytest_demo_2024"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

version = "0.1.0"

[tasks]
cov_install = { cmd = [
    "python", "-m", "pip", "install", "-ve", ".",
    "--no-build-isolation",
    "-Csetup-args=-Dbuildtype=debug",
    "-Csetup-args=-Db_coverage=true",
    "-Cbuilddir=bbdir",
] }

# Run pytest with coverage
cov_test = { cmd = [
    "pytest",
    "--cov=pybtst2024",
    "--cov-report=lcov"
], depends-on = ["cov_install"] }

# Capture coverage data with lcov
lcov_capture = { cmd = [
    "lcov",
    "--output-file", "coverage.cpp",
    "--capture",
    "--directory", "bbdir"
], depends-on = ["cov_test"] }

# Extract coverage data related to the source directory
lcov_extract = { cmd = [
    "lcov",
    "--output-file", "coverage.cpp",
    "--extract", "coverage.cpp", "$PWD/src/*"
], depends-on = ["lcov_capture"] }

# Combine the lcov reports
lcov_combine = { cmd = [
    "sh", "-c", "cat coverage.lcov coverage.cpp > coverage.combined"
], depends-on = ["lcov_extract"] }

cover = { cmd = [
    "lcov",
    "--list", "coverage.combined"
], depends-on = ["lcov_combine"] }

covhtml = { cmd = [
    "genhtml",
    "-o", "covHTML", "coverage.combined"
], depends-on = ["cover"] }

covhttp = { cmd = [
"python", "-m", "http.server", "-d", "covHTML"
], depends-on = ["covhtml"] }


[dependencies]
python = "==3.11"
pip = ">=24.2,<25"
lcov = ">=1.16,<2"
gcovr = ">=5.2,<6"
pdm = ">=2.19.1,<3"
meson = ">=1.5.2,<2"
pkgconfig = ">=1.5.5,<2"
# These are build dependencies, but necessary for pixi run commands with no-build-isolation
compilers = ">=1.8.0,<2"
git = ">=2.46.2,<3"

# Also usually handled with pdm
[pypi-dependencies]
pytest-cov = { version = ">=5.0.0, <6", extras = ["toml"] }
pytest = ">=8.3.3, <9"
ninja = ">=1.11.1.1, <2"
meson-python = "*"
pybind11 = "*"
