default:
  # Minimal pixi image
  image: ghcr.io/prefix-dev/pixi:latest

setup_pixi:
  stage: .pre
  script:
    - pixi install

# Define some compile job to be used as build stage (calls pdm in pixi)
mycompile:
  stage: build
  # Execute command, prefixed with pixi run
  script:
    - pixi run pip install build
    - pixi run python -m build -v

# Define some unit test job to be used as (unit) test stage
myunittest:
  # In Gitlab, stage test   # runs after stage build
  stage: test
  # Execute test command
  script:
    - pixi run pdm sync
    - pixi run pytest
